### ISSUE TITLE
Unable to use, I don't understand where I did it wrong!

### ISSUE THREAD

**Issue by starql** [yomotsu/vuex-history#1]
I use it as an example. When changing the state data, canUndo is always false, no matter whether it is used in the module or directly, there is no error.

**Comment by yomotsu** [comment]
Thanks for your report. Ill fix it later

**Comment by starql** [comment]
非常抱歉，是我的疏忽，我没有仔细阅读说明，没有在更改后 调用 saveSnapshot。 现在已经正常使用了。非常感谢您的插件。 但在实际使用的过程中，我还有一些疑问，我需要的值，涉及到非常多个更改，如果在每次 调用 actions 方法时 同步调用 saveSnapshot，会非常的繁琐，所以我想在vuex 中去掉saveSnapshot 来保存数据，我尝试把 VuexHistory 挂载在 Vue 实例上 在vuex的模块中调用saveSnapshot，但是报错了。

**Comment by starql** [comment]
非常抱歉，是我的疏忽，我没有仔细阅读说明，没有在更改后调用saveSnapshot。现在已经正常使用了。
非常感谢您的插件。但在实际使用的过程中，我还有一些疑问。
       1. 我需要的值，涉及到非常多个更改，如果在每次调用行动方法时同步调用saveSnapshot，会非常的繁琐，所以我想在vuex中去掉saveSnapshot来保存数据，我尝试把VuexHistory挂载在Vue实例上在vuex的模块中调用saveSnapshot，但是报错了，我还未检查错误，我想请问一下我的思路是否可行？

**Comment by starql** [comment]
I am very sorry, it is my negligence, I did not read the instructions carefully, did not call saveSnapshot after the change. It is now in normal use.
Thank you very much for your plugin. But in the process of actual use, I still have some questions.
1. The value I need involves a lot of changes. If you call saveSnapshot synchronously every time you call the action method, it will be very cumbersome, so I want to remove saveSnapshot in vuex to save the data. I tried to mount VuexHistory in On the instance of Vue, saveSnapshot is called in the vuex module, but the error is reported. I have not checked the error. I would like to ask if my idea is feasible.
2. I saw that you mentioned in the description that you can create VuexHistory for multiple data. How can this be achieved? Can you provide a demo?
thank you very much!

**Comment by yomotsu** [comment]
>  it will be very cumbersome

I think you can use `watch`. I prefer manual `saveSnapshot`, because this could be used dragging UI such as slider, position moving, but the state of this kind of UI should be saved at the end of user operation, rather than every move.

> Can you provide a demo?

`watchStateNames` is an array. you can set multiple names.

```
const watchStateNames = [ 'myWatchingValue' ];
const vuexHistory = new VuexHistory( store, watchStateNames, maxHistoryLength );
```

**Comment by starql** [comment]
Thank you, your reply is very valuable. I already know how to use it. Please take a break early and pay attention to your body.

**Comment by yomotsu** [comment]
Thanks too.
Seems all your questions have been solved. closing this issue for now.
